services:
  app:
    build:
      context: ./
      dockerfile: DockerFile
    container_name: php
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www/

  nginx:
    image: nginx:1.25.1-alpine-slim
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d

  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3333:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: eborges
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"   
